### ISSUE TITLE
Bitnami Redis doesn't start up

### ISSUE THREAD

**Issue by megian** [projectsyn/component-argocd#24]
The component default suggest the usage of the Bitnami Redis image instead of the official one, but this doesn't work anymore with the component version v3.0.0.

```
redis 13:13:51.94
redis 13:13:51.94 Welcome to the Bitnami redis container
redis 13:13:51.94 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
redis 13:13:51.95 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
redis 13:13:51.95
redis 13:13:51.95 INFO  ==> ** Starting Redis setup **
redis 13:13:51.96 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redis 13:13:51.96 INFO  ==> Initializing Redis
*mkdir: cannot create directory '/opt/bitnami/redis/tmp': Permission denied*
```
We use internally the images:
```
  argocd:
    images:
      argocd:
        image: 'docker.io/argoproj/argocd'
      redis:
        image: 'docker.io/library/redis'
      kapitan:
        image: 'docker.io/projectsyn/kapitan'
      vault_agent:
        image: 'docker.io/library/vault'
```

## Steps to Reproduce the Problem

  1. Deploy ArgoCD using the component v3.0.0 with the original image paths from the component

## Actual Behavior
Redis doesn't start, because the image doesn't match to the deployment configuration.

## Expected Behavior
Either the Bitnami image support is going to be updated or the component defaults to the Docker Hub images.
