### ISSUE TITLE
Set resource requests & limits

### ISSUE THREAD

**Issue by mhutter** [projectsyn/component-argocd#41]
Set resource requests and limits for CPU and memory resources.

## Context
ArgoCD consumes significant amounts of resources: `argocd-application-controller-0` comes in at 1GB memory and constantly consumes 0.5-1.0 CPUs. This is not reflected in any resource requests, making the job hard for the K8s scheduler.

**Comment by anothertobi** [comment]
Additionally, this leads to ArgoCD having the `BestEffort` QoS class.

Some real world VPA recommendations where `25m` and `262144k` (`250Mi`) are the default per pod minimum (tenant: `t-purple-brook-2904`):
```
argocd-application-controller:
        target:
          cpu: 1311m
          memory: "1738144563"

argocd-redis:
        target:
          cpu: 25m
          memory: 262144k

argocd-repo-server:
      - containerName: vault-agent
        target:
          cpu: 12m
          memory: 131072k
      - containerName: argocd-repo-server
        target:
          cpu: 78m
          memory: 131072k

argocd-server:
        target:
          cpu: 25m
          memory: 262144k
```
